// AUTO-GENERATED by scripts/enrich.ts — do not edit by hand.
// Native-mirror tokens (POL/CELO precompiles, legacy ETH mirrors).
import type { MirrorToken } from "../types.js";
export const MIRROR_TOKENS: readonly MirrorToken[] = [
  { address: "0xdeaddeaddeaddeaddeaddeaddeaddeaddead0000", chainId: 10, coinGeckoId: "ethereum", decimals: 18, name: "Ether", symbol: "ETH", kind: "mirror", mirrors: "native" },
  { address: "0x0000000000000000000000000000000000001010", chainId: 137, coinGeckoId: "polygon-ecosystem-token", decimals: 18, name: "Polygon Ecosystem Token", symbol: "POL", kind: "mirror", mirrors: "native" },
  { address: "0x000000000000000000000000000000000000800a", chainId: 324, coinGeckoId: "ethereum", decimals: 18, name: "Ether", symbol: "ETH", kind: "mirror", mirrors: "native" },
  { address: "0xdeaddeaddeaddeaddeaddeaddeaddeaddead0000", chainId: 8453, coinGeckoId: "ethereum", decimals: 18, name: "Ether", symbol: "ETH", kind: "mirror", mirrors: "native" },
  { address: "0x471ece3750da237f93b8e339c536989b8978a438", chainId: 42220, decimals: 18, name: "Celo native asset", symbol: "CELO", kind: "mirror", mirrors: "native" },
];
