// Pure codegen (no network): classifies enriched tokens by precedence
// (stablecoin > wrapped > mirror > standard) and emits the four data modules
// under src/tokens/data/. Invoked by enrich.ts after fetch (or with --cached).
//
// Invariants (non-empty symbol, integer decimals in 0..36, valid address, no
// undocumented drops) are enforced HERE at the generation boundary, so a bad
// on-chain read fails the regenerate loudly instead of shipping silently.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { CHAINS } from "../src/chains/chains.js";
import type { StablecoinFamily } from "./classification.js";
import { DROPPED, FORCE_BRIDGED, STABLECOIN_FAMILIES, TICKER_OVERRIDES } from "./classification.js";
import type { EnrichedToken } from "./enrich.js";

const DATA_DIR = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "tokens", "data");

/** cryptfolio CoinGeckoId map: ticker -> CoinGecko coin id. */
const COINGECKO_ID: Partial<Record<string, string>> = {
  AAVE: "aave",
  ARB: "arbitrum",
  ATOM: "cosmos",
  AVAIL: "avail",
  AVAX: "avalanche-2",
  BERA: "berachain-bera",
  BNB: "binancecoin",
  CHZ: "chiliz",
  DYDX: "dydx",
  DYN: "dymension",
  EIGEN: "eigenlayer",
  ENS: "ethereum-name-service",
  ETH: "ethereum",
  FUEL: "fuel-network",
  GRT: "the-graph",
  HYPE: "hyperliquid",
  MKR: "maker",
  MON: "monad",
  OP: "optimism",
  POL: "polygon-ecosystem-token",
  PROVE: "succinct",
  S: "sonic-3",
  SAFE: "safe",
  SOL: "solana",
  SOPH: "sophon",
  STRK: "starknet",
  TIA: "celestia",
  XDC: "xdce-crowd-sale",
  ZEC: "zcash",
  ZK: "zksync",
};

const ADDRESS_RE = /^0x[0-9a-f]{40}$/;
const NAME_LOOKS_BRIDGED = /\b(bridge|bridged|pos)\b/i;
const MAX_DECIMALS = 36;

const key = (chainId: number, address: string) => `${chainId}:${address.toLowerCase()}`;
const slugToChainId = new Map(CHAINS.map((c) => [c.slug, c.chainId]));
const slugByChainId = new Map(CHAINS.map((c) => [c.chainId, c.slug]));

function chainIdForSlug(slug: string, source: string): number {
  const chainId = slugToChainId.get(slug);
  if (chainId === undefined) throw new Error(`unknown chain slug in ${source}: ${slug}`);
  return chainId;
}

type NativeMeta = { symbol: string; name: string; decimals: number };

/** key -> stablecoin family (from each family's canonical contracts allowlist). */
const stablecoinByKey = new Map<string, StablecoinFamily>();
/** exact on-chain symbol -> stablecoin family (catches bridged/legacy variants). */
const stablecoinBySymbol = new Map<string, StablecoinFamily>();
for (const family of STABLECOIN_FAMILIES) {
  for (const symbol of family.symbols) stablecoinBySymbol.set(symbol, family);
  for (const [slug, addresses] of Object.entries(family.contracts ?? {})) {
    const chainId = chainIdForSlug(slug, `stablecoin family ${family.display}`);
    for (const address of addresses) stablecoinByKey.set(key(chainId, address), family);
  }
}

/** key -> native-wrap underlying symbol (the chain's native gas token). */
const nativeWrapKeys = new Map<string, string>();
const nativeByChain = new Map<number, NativeMeta>();
for (const chain of CHAINS) {
  nativeByChain.set(chain.chainId, {
    decimals: chain.nativeCurrency.decimals,
    name: chain.nativeCurrency.name,
    symbol: chain.nativeCurrency.symbol,
  });
  if (chain.wrappedNativeAddress) {
    nativeWrapKeys.set(key(chain.chainId, chain.wrappedNativeAddress), chain.nativeCurrency.symbol);
  }
}

const mirrorKeys = new Set<string>();
for (const chain of CHAINS) {
  for (const mirror of chain.mirrorAddresses ?? []) mirrorKeys.add(key(chain.chainId, mirror));
}

const droppedKeys = new Set<string>();
for (const d of DROPPED) {
  droppedKeys.add(key(chainIdForSlug(d.chain, "DROPPED"), d.address));
}

const forceBridged = new Set(FORCE_BRIDGED.map((s) => s.toLowerCase()));
const BARE_TICKER_RE = /^[A-Za-z0-9][A-Za-z0-9_.-]*$/;

const coinGeckoIdFor = (symbol: string): string | undefined => COINGECKO_ID[symbol.toUpperCase()];

const str = (v: string) => JSON.stringify(v);

type TokenFields = [string, string | undefined][];
type Bucket = "stablecoin" | "wrapped" | "mirror" | "standard";
type Resolved = { decimals: number; symbol: string; name: string | null };

/** Render one object literal from key/value source fragments (skips undefined). */
function renderObject(fields: TokenFields): string {
  const body = fields
    .filter(([, v]) => v !== undefined)
    .map(([k, v]) => `${k}: ${v}`)
    .join(", ");
  return `  { ${body} },`;
}

function header(title: string, typeImports: string): string {
  return [
    "// AUTO-GENERATED by scripts/enrich.ts — do not edit by hand.",
    `// ${title}`,
    `import type { ${typeImports} } from "../types.js";`,
    "",
  ].join("\n");
}

/** Resolve decimals/symbol/name, applying a native fallback for unreadable mirrors. */
function resolveMetadata(t: EnrichedToken): Resolved | null {
  if (t.decimals !== null) return { decimals: t.decimals, name: t.name, symbol: t.symbol ?? "" };
  if (mirrorKeys.has(key(t.chainId, t.address))) {
    const native = nativeByChain.get(t.chainId);
    if (native) {
      return {
        decimals: native.decimals,
        name: t.name ?? native.name,
        symbol: t.symbol || native.symbol,
      };
    }
  }
  return null;
}

/** Throw if an emitted token would violate a registry invariant. */
function assertValid(t: EnrichedToken, meta: Resolved): void {
  const at = `${t.slug} ${t.address}`;
  const expectedSlug = slugByChainId.get(t.chainId);
  if (expectedSlug === undefined) throw new Error(`unknown chain id (${t.chainId}): ${at}`);
  if (t.slug !== expectedSlug) {
    throw new Error(`chain id/slug mismatch (${t.chainId} is ${expectedSlug}): ${at}`);
  }
  if (!ADDRESS_RE.test(t.address)) throw new Error(`invalid address: ${at}`);
  if (!meta.symbol) throw new Error(`empty symbol: ${at} (decimals read but symbol unreadable)`);
  if (!Number.isInteger(meta.decimals) || meta.decimals < 0 || meta.decimals > MAX_DECIMALS) {
    throw new Error(`decimals out of range (${meta.decimals}): ${at}`);
  }
}

/** Classify a resolved token into its data-file bucket and render its literal. */
function classify(t: EnrichedToken, meta: Resolved): { bucket: Bucket; line: string } {
  const k = key(t.chainId, t.address);
  const coinGeckoId = coinGeckoIdFor(meta.symbol);
  const base: TokenFields = [
    ["address", str(t.address)],
    ["chainId", String(t.chainId)],
    ["coinGeckoId", coinGeckoId ? str(coinGeckoId) : undefined],
    ["decimals", String(meta.decimals)],
    ["name", meta.name ? str(meta.name) : undefined],
    ["symbol", str(meta.symbol)],
  ];

  const family = stablecoinByKey.get(k) ?? stablecoinBySymbol.get(meta.symbol);
  if (family) {
    const ticker = TICKER_OVERRIDES[k] ?? meta.symbol;
    if (!BARE_TICKER_RE.test(ticker)) {
      throw new Error(
        `invalid stablecoin ticker ${str(ticker)} for ${t.slug} ${t.address}; add a TICKER_OVERRIDES entry in classification.ts`
      );
    }
    const bridged =
      !family.nativeSymbols.includes(meta.symbol) ||
      NAME_LOOKS_BRIDGED.test(meta.name ?? "") ||
      forceBridged.has(k);
    const line = renderObject([
      ...base,
      ["backing", str(family.backing)],
      ["bridged", String(bridged)],
      ["issuer", str(family.issuer)],
      ["kind", str("stablecoin")],
      ["peg", str(family.peg)],
      ["ticker", str(ticker)],
    ]);
    return { bucket: "stablecoin", line };
  }

  const nativeWrap = nativeWrapKeys.get(k);
  if (nativeWrap !== undefined) {
    const line = renderObject([
      ...base,
      ["kind", str("wrapped")],
      ["underlyingSymbol", str(nativeWrap)],
    ]);
    return { bucket: "wrapped", line };
  }

  if (mirrorKeys.has(k)) {
    return {
      bucket: "mirror",
      line: renderObject([...base, ["kind", str("mirror")], ["mirrors", str("native")]]),
    };
  }

  return { bucket: "standard", line: renderObject([...base, ["kind", str("standard")]]) };
}

export function generate(tokens: EnrichedToken[]): void {
  const all = [...tokens].sort(
    (a, b) => a.chainId - b.chainId || a.address.localeCompare(b.address)
  );

  const buckets: Record<Bucket, string[]> = {
    mirror: [],
    stablecoin: [],
    standard: [],
    wrapped: [],
  };
  const seen = new Set<string>();
  let droppedCount = 0;

  for (const t of all) {
    const k = key(t.chainId, t.address);
    if (seen.has(k)) continue;
    const meta = resolveMetadata(t);
    if (!meta) {
      if (droppedKeys.has(k)) {
        droppedCount++;
        continue;
      }
      throw new Error(
        `unresolved & undocumented token ${t.slug} ${t.address}: read it on-chain and add to a stablecoin family, MANUAL_TOKENS, or DROPPED in classification.ts`
      );
    }
    assertValid(t, meta);
    seen.add(k);
    const { bucket, line } = classify(t, meta);
    buckets[bucket].push(line);
  }

  const files: [string, string, string, string[]][] = [
    [
      "stablecoins.ts",
      "Stablecoins (USDC/USDT/DAI/EURe/BUSD/TUSD/GUSD/EURT/USDB/sUSD) and bridged variants.",
      "Stablecoin",
      buckets.stablecoin,
    ],
    [
      "wrapped.ts",
      "Wrapped native tokens (WETH/WAVAX/WBNB/…) — one canonical wrap per chain.",
      "WrappedToken",
      buckets.wrapped,
    ],
    [
      "mirrors.ts",
      "Native-mirror tokens (POL/CELO precompiles, legacy ETH mirrors).",
      "MirrorToken",
      buckets.mirror,
    ],
    [
      "standard.ts",
      "Standard ERC-20s enriched from the included.tsv holdings set.",
      "StandardToken",
      buckets.standard,
    ],
  ];

  const exportName: Record<string, string> = {
    "mirrors.ts": "MIRROR_TOKENS",
    "stablecoins.ts": "STABLECOINS",
    "standard.ts": "STANDARD_TOKENS",
    "wrapped.ts": "WRAPPED_TOKENS",
  };

  for (const [file, title, typeName, entries] of files) {
    const content = `${header(title, typeName)}export const ${exportName[file]}: readonly ${typeName}[] = [\n${entries.join("\n")}\n];\n`;
    writeFileSync(join(DATA_DIR, file), content);
    console.log(`  ${file}: ${entries.length} tokens`);
  }
  console.log(`  (dropped ${droppedCount} documented un-enrichable tokens)`);
}
