// Hand-authored accounting-facing ticker vocabulary (NOT generated by
// scripts/enrich.ts). Kept here so the "what counts as a stablecoin" and
// "what does a wrapped ticker price against" questions have one canonical home.

import type { StablecoinPeg } from "./types.js";

/**
 * Historical ticker spellings that identify the same asset and unit system.
 *
 * Keys are legacy/provider spellings and values are the current accounting
 * ticker. Migrations with a unit change or separate accounting pools do not
 * belong here.
 */
export const CANONICAL_TICKER_ALIASES: Readonly<Record<string, string>> = {
  HAV: "SNX",
  INST: "FLUID",
  MATIC: "POL",
  XNO: "NANO",
  XRB: "NANO",
};

/**
 * Fiat-pegged quote tickers, grouped by peg currency.
 *
 * This is the canonical, chain-agnostic vocabulary of ticker symbols treated as
 * fiat-equivalent when valuing a trade's quote side. It is deliberately a
 * curated *superset* of the on-chain stablecoin symbols in the {@link STABLECOINS}
 * data (accessible via {@link getStablecoins}): it also folds in the plain fiat
 * quote `USD`, fiat-collateralized native tokens on Gnosis (`xDAI` /
 * `WxDAI`), exchange- or issuer-specific pegged tickers (`BSC-USD`,
 * `LinkUSD`, `mUSD`) that never appear as canonical on-chain ERC-20 symbols,
 * and non-EVM bridged variants (`axlUSDC` on Cosmos chains, `lzUSDC` on
 * Aptos).
 *
 * Conversely it intentionally omits the on-chain stablecoin tickers `TUSD`,
 * `USDB`, `EURT`, `USDT-matic`, and `BUSD-bsc`, which remain quote-only
 * downstream.
 *
 * Membership tests against these tickers are **case-sensitive**, so preserve
 * the exact casing.
 */
export const STABLECOIN_TICKERS_BY_PEG: Readonly<Record<StablecoinPeg, readonly string[]>> = {
  EUR: ["EURe"],
  USD: [
    "axlUSDC",
    "BSC-USD",
    "BUSD",
    "DAI",
    "DAI.e",
    "frxUSD",
    "GUSD",
    "ioUSDC",
    "LinkUSD",
    "lzUSDC",
    "mUSD",
    "USD",
    "USDC",
    "USDC.e",
    "USDbC",
    "USDT",
    "USDT0",
    "USDt",
    "WxDAI",
    "xDAI",
    "pUSD",
  ],
};

/**
 * Maps a wrapped or otherwise decorated ticker to the raw asset whose USD price
 * series should value it. Wrapped tokens keep their own accounting pools, but
 * their market price is the underlying asset's price.
 *
 * A curated *superset* of the on-chain wrapped-native relation (a
 * {@link WrappedToken}'s `underlyingSymbol`): it also covers cross-chain bridged
 * wraps (`WBNB.b`), the legacy Polygon name (`WMATIC`), and non-native wrappers
 * priced at the underlying (`WBTC`, `WCELO`, `clBTC`, `wNXM`). Keys are matched
 * **case-sensitively** by design.
 */
export const PRICE_ASSET_ALIASES: Readonly<Record<string, string>> = {
  COREBTC: "BTC",
  clBTC: "BTC",
  ioETH: "ETH",
  WAVAX: "AVAX",
  WBERA: "BERA",
  WBNB: "BNB",
  "WBNB.b": "BNB",
  WBTC: "BTC",
  WCELO: "CELO",
  WEGLD: "EGLD",
  WETH: "ETH",
  WFRAX: "FRAX",
  WFTM: "FTM",
  WHYPE: "HYPE",
  WIOTX: "IOTX",
  WMATIC: "POL",
  WMON: "MON",
  WPOL: "POL",
  WSEI: "SEI",
  WXDC: "XDC",
  WxDAI: "xDAI",
  wfrxETH: "frxETH",
  wNXM: "NXM",
  wSOL: "SOL",
};

/**
 * Canonical source-ref chain for native gas assets, keyed by accounting ticker.
 *
 * This is intentionally ticker-level rather than `(chain, ticker)` data: callers
 * should prefer the row's chain first, then use this fallback only when a
 * cross-chain source cell explicitly includes the native-chain transaction ref.
 * Values match the accounting ledger's `chain` vocabulary and are compared
 * case-insensitively by downstream source-ref helpers.
 */
export const NATIVE_ASSET_CHAINS: Readonly<Record<string, string>> = {
  AVAX: "Avalanche",
  BNB: "BNB Chain",
  BTC: "Bitcoin",
  EOS: "EOS",
  ETH: "Ethereum",
  FRAX: "Fraxtal",
  frxETH: "Fraxtal",
  HBAR: "Hedera",
  NEO: "NEO",
  POL: "Polygon",
  SC: "Sia",
  SOL: "Solana",
  STEEM: "Steem",
  XRP: "XRP",
  xDAI: "Gnosis",
};
