// Hand-authored accounting-facing ticker vocabulary (NOT generated by
// scripts/enrich.ts). Kept here so the "what counts as a stablecoin" and
// "what does a wrapped ticker price against" questions have one canonical home.

import type { StablecoinPeg } from "./types.js";

/**
 * Fiat-pegged quote tickers, grouped by peg currency.
 *
 * This is the canonical, chain-agnostic vocabulary of ticker symbols treated as
 * fiat-equivalent when valuing a trade's quote side. It is deliberately a
 * curated *superset* of the on-chain stablecoin symbols in the {@link STABLECOINS}
 * data (accessible via {@link getStablecoins}): it also folds in the plain fiat
 * quote `USD`, fiat-collateralized native tokens on Gnosis (`xDAI` / `XDAI` /
 * `WXDAI`), and exchange- or issuer-specific pegged tickers (`BSC-USD`,
 * `LinkUSD`, `mUSD`) that never appear as canonical on-chain ERC-20 symbols.
 *
 * Conversely it intentionally omits several on-chain stablecoin symbols
 * (`TUSD`, `USDB`, bridged `USDC.e` / `USDbC`, …) that are not part of the
 * fiat-equivalent quote vocabulary.
 *
 * Membership tests against these tickers are **case-sensitive** — `xDAI` and
 * `XDAI` are both listed on purpose — so preserve the exact casing.
 */
export const STABLECOIN_TICKERS_BY_PEG: Readonly<Record<StablecoinPeg, readonly string[]>> = {
  EUR: ["EURe"],
  USD: [
    "BSC-USD",
    "BUSD",
    "DAI",
    "GUSD",
    "LinkUSD",
    "mUSD",
    "sUSD",
    "USD",
    "USDC",
    "USDT",
    "WXDAI",
    "XDAI",
    "xDAI",
  ],
};

/**
 * Maps a wrapped or otherwise decorated ticker to the raw asset whose USD price
 * series should value it. Wrapped tokens keep their own accounting pools, but
 * their market price is the underlying asset's price.
 *
 * A curated *superset* of the on-chain wrapped-native relation (a
 * {@link WrappedToken}'s `underlyingSymbol`): it also covers cross-chain bridged
 * wraps (`WBNB.b`), the legacy Polygon name (`WMATIC`), non-native wrappers
 * priced at the underlying (`WBTC`, `WCELO`, `clBTC`, `wNXM`), and the lowercase
 * `wxDAI` variant. Keys are matched **case-sensitively** by design (`WXDAI` maps
 * to `xDAI`, mirroring the accounting ledger's lowercase Gnosis native ticker).
 */
export const PRICE_ASSET_ALIASES: Readonly<Record<string, string>> = {
  clBTC: "BTC",
  WAVAX: "AVAX",
  WBERA: "BERA",
  WBNB: "BNB",
  "WBNB.b": "BNB",
  WBTC: "BTC",
  WCELO: "CELO",
  WETH: "ETH",
  WFTM: "FTM",
  WHYPE: "HYPE",
  WMATIC: "POL",
  WMON: "MON",
  WPOL: "POL",
  WSEI: "SEI",
  WXDAI: "xDAI",
  WXDC: "XDC",
  wNXM: "NXM",
  wxDAI: "xDAI",
};

/**
 * Canonical source-ref chain for native gas assets, keyed by accounting ticker.
 *
 * This is intentionally ticker-level rather than `(chain, ticker)` data: callers
 * should prefer the row's chain first, then use this fallback only when a
 * cross-chain source cell explicitly includes the native-chain transaction ref.
 * Values match the accounting ledger's `chain` vocabulary and are compared
 * case-insensitively by downstream source-ref helpers.
 */
export const NATIVE_ASSET_CHAINS: Readonly<Record<string, string>> = {
  AVAX: "Avalanche",
  BNB: "BNB Chain",
  BTC: "Bitcoin",
  EOS: "EOS",
  ETH: "Ethereum",
  NEO: "NEO",
  POL: "Polygon",
  SC: "Sia",
  SOL: "Solana",
  STEEM: "Steem",
  XRP: "XRP",
  xDAI: "Gnosis",
};
